HTTP/1.1 200 OK
Content-Type: application/json;charset=utf-8
Content-Length: 7554
Content-Encoding: gzip
Vary: Accept-Encoding
X-Json: 1
X-Node: 127.0.0.1
Expires: Sun, 23 May 2021 10:18:05 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sun, 23 May 2021 10:18:05 GMT
Connection: close

{
  "template": "serverbrowserwarsaw.warsawindex",
  "globalContext": {
    "currentUrl": "|bf4|servers",
    "isAjaxFetch": false,
    "currentCanonicalURL": "http:\/\/battlelog.battlefield.com\/bf4\/serverbrowserwarsaw",
    "useIdentity2RedirectFlow": true,
    "servers": [
      {
        "map": "MP_Siege",
        "gameId": "36028797037526234",
        "gameExpansions": [
          0,
          524288,
          17179869184,
          268435456,
          1048576,
          8388608,
          4194304
        ],
        "mapMode": "2097152",
        "ip": "",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 14
          }
        },
        "guid": "5a2ff1b1-2b99-4964-9df8-ad7620e7e73b",
        "port": 0,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "Private Gaming Nights Server -",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 8,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 1,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "e13e57be:5066b0c79b143630fdbeda8e63933d39ab4b2e69",
        "preset": 1,
        "pingSite": "ams",
        "country": "ie"
      },
      {
        "map": "MP_Journey",
        "gameId": "18014398528053979",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "94.250.199.60",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 18
          },
          "4": {
            "current": 0,
            "max": 2
          }
        },
        "guid": "9cf57f4e-9e18-4176-9d8b-90b5e895aa38",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "24\/7 Golmud UKSASDD",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "ams",
        "country": "gb"
      },
      {
        "map": "XP7_Valley",
        "gameId": "18014398528038102",
        "gameExpansions": [
          17179869184,
          0,
          8589934592
        ],
        "mapMode": "64",
        "ip": "216.155.140.200",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 1,
            "max": 10
          }
        },
        "guid": "584c6272-8bff-4671-ad3b-70a7102e0d93",
        "port": 30000,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "17179869184",
        "name": "[EOTC]- BOOTCAMP FOR NOOBS-1P START-ADMINS ON DUTY-",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 45,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "iad",
        "country": "ca"
      },
      {
        "map": "XP2_003",
        "gameId": "36028797037512925",
        "gameExpansions": [
          2097152,
          0,
          1048576,
          524288,
          8388608,
          4194304
        ],
        "mapMode": "32",
        "ip": "108.61.227.157",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 4
          }
        },
        "guid": "7a9e1b40-73c1-4e67-9396-167cceb33d32",
        "port": 30010,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "2097152",
        "name": "Troffy",
        "settings": {},
        "fairfight": 1,
        "region": 64,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "syd",
        "country": "au"
      },
      {
        "map": "MP_Abandoned",
        "gameId": "36028797037526223",
        "gameExpansions": [
          0
        ],
        "mapMode": "512",
        "ip": "62.104.179.1",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 16
          }
        },
        "guid": "fcb93459-7fb6-4353-ae13-6d2ceacf79f0",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "K und M @ 4Netplayers",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Prison",
        "gameId": "18014398528052515",
        "gameExpansions": [
          0
        ],
        "mapMode": "32",
        "ip": "43.239.136.72",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 20
          }
        },
        "guid": "884a13ac-0800-46c0-a3d0-17b962e3ab64",
        "port": 25610,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "i3D.net  - Practice Server -",
        "settings": {},
        "fairfight": 0,
        "region": 32,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 4,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "nrt",
        "country": "hk"
      },
      {
        "map": "MP_Siege",
        "gameId": "36028797037526288",
        "gameExpansions": [
          0
        ],
        "mapMode": "2",
        "ip": "104.153.105.213",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 1,
            "max": 4
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 38
          }
        },
        "guid": "62d308f4-f9c0-43fb-8452-7113362f840a",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "BF4 Game Time - Newcomer server - NFOservers.com - Chicago # 08",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 1,
        "experience": 2,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "iad",
        "country": "us"
      },
      {
        "map": "MP_Siege",
        "gameId": "36028797037526122",
        "gameExpansions": [
          0
        ],
        "mapMode": "32",
        "ip": "62.104.177.186",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 1
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 6,
            "max": 10
          }
        },
        "guid": "489c0017-7415-4605-85c1-b38207037196",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "4Netplayers Paintball war gestern",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 3,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Prison",
        "gameId": "36028797037526126",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "194.97.167.121",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 4
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 28
          }
        },
        "guid": "1666c961-afd3-455c-adbf-560eee7ffce7",
        "port": 25200,
        "punkbuster": 0,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "ZIFFEX Network",
        "settings": {},
        "fairfight": 0,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 4,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "ams",
        "country": "nl"
      },
      {
        "map": "XP0_Metro",
        "gameId": "18014398528038556",
        "gameExpansions": [
          524288
        ],
        "mapMode": "2",
        "ip": "135.148.53.110",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 32
          }
        },
        "guid": "2b4b1736-4312-4d84-aced-0fb5898d05ec",
        "port": 25400,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "524288",
        "name": "Hardcore Rush Test",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 2,
        "pingSite": "iad",
        "country": "us"
      },
      {
        "map": "MP_Tremors",
        "gameId": "36028797037512896",
        "gameExpansions": [
          0,
          2097152
        ],
        "mapMode": "1024",
        "ip": "",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 18
          }
        },
        "guid": "a6138103-8e65-4ea6-b022-47468797cd58",
        "port": 0,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "vN 8 vs 8 Area",
        "settings": {},
        "fairfight": 0,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 8,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 1,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "3782e387:68362bec683110dcd237f32baa1ea42a90647358",
        "preset": 8,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Journey",
        "gameId": "18014398528038328",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "104.153.105.74",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765079,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 59,
            "max": 64
          },
          "4": {
            "current": 1,
            "max": 2
          }
        },
        "guid": "cfa68ec0-a030-4247-90e1-9b643a71edcd",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "! RC1-24\/7GOLMUD",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "iad",
        "country": "us"
      },
      {
        "map": "XP7_Valley",
        "gameId": "36028797037526054",
        "gameExpansions": [
          17179869184
        ],
        "mapMode": "64",
        "ip": "",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 6
          },
          "4": {
            "current": 0,
            "max": 2
          }
        },
        "guid": "7137e509-c143-4e30-b25d-0cc8ac26b31e",
        "port": 0,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "17179869184",
        "name": "Dice LA Camo Unlock Server",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 4,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 1,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "3529bb15:3df3aeb53d698d9f9da4dba0ec5e36189c3539e5",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "XP3_MarketPl",
        "gameId": "18014398528054075",
        "gameExpansions": [
          4194304
        ],
        "mapMode": "64",
        "ip": "5.101.165.195",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 32
          }
        },
        "guid": "6890825e-311b-4fdf-8414-7f3f6d50b96b",
        "port": 32200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "4194304",
        "name": "=I.N.E.S.= Hardcore & Inf. only!",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "XP7_Valley",
        "gameId": "36028797037526269",
        "gameExpansions": [
          17179869184
        ],
        "mapMode": "64",
        "ip": "",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 10
          }
        },
        "guid": "a940248a-3a80-4a07-b6d6-f8a017566d60",
        "port": 0,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "17179869184",
        "name": "Flapjax Gaming",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 8,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 1,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "59b2a60e:92393a8f1ce9bb72b0f50e2ed35f305febda1c07",
        "preset": 8,
        "pingSite": "iad",
        "country": "us"
      },
      {
        "map": "MP_Siege",
        "gameId": "36028797037524943",
        "gameExpansions": [
          0,
          524288,
          1048576,
          2097152,
          4194304,
          8388608,
          8589934592,
          17179869184
        ],
        "mapMode": "512",
        "ip": "185.189.255.242",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765085,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 8,
            "max": 64
          }
        },
        "guid": "3917f9d8-0079-49ac-bbef-f72bbdb8ce43",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "7YA CLAN__HARDCORE__24\/7 ALL MAPS\/\/ MIX MAP MODE!!!",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 2,
        "pingSite": "ams",
        "country": "ru"
      },
      {
        "map": "XP7_Valley",
        "gameId": "36028797037524362",
        "gameExpansions": [
          17179869184,
          0,
          1048576,
          524288,
          2097152,
          8589934592,
          4194304
        ],
        "mapMode": "1024",
        "ip": "108.61.125.61",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 24
          }
        },
        "guid": "a0cd12a8-950d-46ef-ac03-bad80018fe86",
        "port": 30000,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "17179869184",
        "name": "KILLEM & CHILLEM # 1 - 60hz - ( TDM\/DOM\/CA\/CQL\/CTF )",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "iad",
        "country": "us"
      },
      {
        "map": "MP_Abandoned",
        "gameId": "18014398528054213",
        "gameExpansions": [
          0
        ],
        "mapMode": "32",
        "ip": "",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 10
          }
        },
        "guid": "aa7da849-8ad1-48db-bcb8-c7b48cbf583d",
        "port": 0,
        "punkbuster": 0,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "Gaminggruppe Luetten",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 8,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 1,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "7b3abfb8:106597ebaefd8bbeb61c5c1a41662b58ad6c1c6d",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Tremors",
        "gameId": "18014398528054091",
        "gameExpansions": [
          0,
          1048576,
          4194304,
          2097152
        ],
        "mapMode": "64",
        "ip": "",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 8
          }
        },
        "guid": "4231246c-8f3a-4b15-8c4e-1c53a35a0410",
        "port": 0,
        "punkbuster": 0,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "Backwasch 1v1 Langeweile",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 4,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 1,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "641ad937:cd17ac33fa58451464bb843744ef6e7e69ff5595",
        "preset": 8,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Tremors",
        "gameId": "36028797037525757",
        "gameExpansions": [
          0,
          524288,
          1048576,
          268435456,
          2097152,
          4194304,
          8388608,
          8589934592,
          17179869184
        ],
        "mapMode": "32",
        "ip": "108.61.109.89",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 22
          }
        },
        "guid": "86aafa86-3532-4927-a398-d74f3dc02920",
        "port": 30020,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "Frigginoldguys TDM & Mix Hardcore!",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 2,
        "pingSite": "lax",
        "country": "us"
      },
      {
        "map": "MP_Siege",
        "gameId": "18014398528054170",
        "gameExpansions": [
          0,
          8589934592,
          8388608,
          17179869184
        ],
        "mapMode": "64",
        "ip": "194.97.167.235",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 48
          }
        },
        "guid": "55f30338-7447-41bd-aeaa-19a14a002055",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "[GFTP] All Maps (Active Admins) 4Netplayers.net",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "XP7_Valley",
        "gameId": "18014398528054297",
        "gameExpansions": [
          17179869184,
          0,
          268435456,
          1048576,
          8589934592,
          2097152
        ],
        "mapMode": "2",
        "ip": "162.248.92.96",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 12
          }
        },
        "guid": "7ee94187-a428-4eb3-bbdc-9ad7dafc69e4",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "17179869184",
        "name": "It Is Always A Game",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "iad",
        "country": "us"
      },
      {
        "map": "XP0_Caspian",
        "gameId": "36028797037525540",
        "gameExpansions": [
          524288
        ],
        "mapMode": "64",
        "ip": "94.250.194.98",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 1
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 32
          }
        },
        "guid": "6c422faf-7dff-4d81-9d4a-e45b6c7f6a2f",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "524288",
        "name": "# Prinz Caspian by [KP] | CASPIAN BORDER 2014 ONLY | 1P START",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Prison",
        "gameId": "36028797037490259",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "49.12.51.105",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 64
          }
        },
        "guid": "ee6f326f-4cb8-46c6-ab43-c69c70e8e07b",
        "port": 25300,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "24\/7 | METRO | EPS 60 hz | EPG.GG",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Prison",
        "gameId": "36028797037524205",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 8
          },
          "4": {
            "current": 0,
            "max": 2
          }
        },
        "guid": "b2187797-3d81-4997-bc58-e732e49f9153",
        "port": 0,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "A new GameServers.com BF4 Server!",
        "settings": {},
        "fairfight": 0,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 8,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "ams",
        "country": "gb"
      },
      {
        "map": "MP_Tremors",
        "gameId": "18014398528054287",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "85.190.158.71",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 20
          }
        },
        "guid": "fa572e34-247a-42da-b72f-38b5652d023e",
        "port": 30000,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "HAPPY LAND Server - Be respectful",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "iad",
        "country": "us"
      },
      {
        "map": "MP_Prison",
        "gameId": "18014398528053340",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "135.148.52.225",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 64
          }
        },
        "guid": "17ce9ef1-9510-4279-8cf2-4fa9aebe63e8",
        "port": 25500,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "!  [APEX] 24\/7 CONQUEST | 60 HZ | BEST MAPS + DLC",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 1,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "iad",
        "country": "us"
      },
      {
        "map": "MP_Siege",
        "gameId": "18014398528052966",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "185.189.255.243",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765082,
        "slots": {
          "8": {
            "current": 0,
            "max": 4
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 2,
            "max": 64
          },
          "4": {
            "current": 0,
            "max": 2
          }
        },
        "guid": "4d424f34-38ed-4432-be09-9e5d4c550dcf",
        "port": 25600,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "24\/7 | City Assault | Battlefield Server | EPS 60 hz | EPG.GG",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "XP0_Metro",
        "gameId": "18014398528019052",
        "gameExpansions": [
          524288
        ],
        "mapMode": "1",
        "ip": "",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 8
          }
        },
        "guid": "d0915c75-d7e0-4714-b0f3-cbda79e70b48",
        "port": 0,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "524288",
        "name": "BFlag In 2021 Imagine",
        "settings": {},
        "fairfight": 0,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 4,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 1,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "586c2fb7:bfe7820d37b7d3f74d74e5049db4aaaca5357b7e",
        "preset": 8,
        "pingSite": "iad",
        "country": "us"
      },
      {
        "map": "XP4_SubBase",
        "gameId": "18014398528054157",
        "gameExpansions": [
          8388608,
          0,
          1048576,
          524288,
          268435456,
          2097152,
          8589934592,
          17179869184
        ],
        "mapMode": "1",
        "ip": "176.57.170.48",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 32
          }
        },
        "guid": "2a6e4a80-7df1-4a1a-a4ce-d0cbed4dc55f",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "8388608",
        "name": "DevilsWorld \/ BF4 ist unsere Hoelle \/ K\/D bis 1.6 \/ 60 Hz",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Abandoned",
        "gameId": "36028797037525367",
        "gameExpansions": [
          0,
          524288,
          1048576,
          2097152,
          8388608,
          8589934592,
          4194304
        ],
        "mapMode": "64",
        "ip": "186.233.187.32",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 64
          }
        },
        "guid": "d0893e7e-cf91-4b85-894c-38140c43aa4c",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "! The BoneZone | Conquest All Maps 60hz",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "iad",
        "country": "us"
      },
      {
        "map": "MP_Siege",
        "gameId": "36028797037512932",
        "gameExpansions": [
          0,
          524288,
          1048576,
          2097152,
          8388608,
          8589934592,
          4194304
        ],
        "mapMode": "8",
        "ip": "94.250.199.11",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 4
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 6
          }
        },
        "guid": "a08b220b-2470-450a-bcb7-cf51a1569994",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "Swamp",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "XP4_Arctic",
        "gameId": "36028797037526093",
        "gameExpansions": [
          8388608,
          524288
        ],
        "mapMode": "64",
        "ip": "94.250.208.28",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765072,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 53,
            "max": 64
          }
        },
        "guid": "18b3fdf2-11c5-4156-8175-8553e2f50576",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "8388608",
        "name": "SUPER@ [SiC] S3 Second Assault \/ Final Stand Conquest All Maps",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "XP1_002",
        "gameId": "36028797037526091",
        "gameExpansions": [
          1048576,
          0,
          2097152,
          17179869184,
          4194304
        ],
        "mapMode": "1024",
        "ip": "5.101.165.4",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 10
          }
        },
        "guid": "d9c37cf9-6d8e-4d07-b067-5efabc67f6c6",
        "port": 32200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "1048576",
        "name": "[ SHC] Schweizer Hardcore Clan | Infanterie #Rules LIVE Server",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 2,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Naval",
        "gameId": "18014398528054212",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "176.57.170.14",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765085,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 64
          }
        },
        "guid": "135a9ba4-51a2-4722-8066-462e24f44e34",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "!!-<{Blueberry Pancakes}>-!! # No Lag - Vanilla # 60hz",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Prison",
        "gameId": "36028797037526102",
        "gameExpansions": [
          0,
          8589934592
        ],
        "mapMode": "512",
        "ip": "94.250.199.69",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 32
          }
        },
        "guid": "70241ab1-0e15-40c4-9661-92ddbfda611e",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "#1|GGE|Everyone is welcome| NoWeaponRules| All Maps| All DLCs",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 2,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Siege",
        "gameId": "18014398528040579",
        "gameExpansions": [
          0,
          1048576
        ],
        "mapMode": "64",
        "ip": "94.250.199.56",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 30
          },
          "4": {
            "current": 0,
            "max": 2
          }
        },
        "guid": "2a68059a-9587-4857-b541-eb245a95b07f",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "Classic Maps. 60Hz, EU, No rules play how you like.",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "gb"
      },
      {
        "map": "MP_Journey",
        "gameId": "18014398528052505",
        "gameExpansions": [
          0
        ],
        "mapMode": "1",
        "ip": "46.251.234.2",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 20
          }
        },
        "guid": "f587bb62-e98e-40ad-adb2-ae82ec98a926",
        "port": 35200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "LUNA | CONQUEST SMALL | MAP VOTE",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "gb"
      },
      {
        "map": "MP_Damage",
        "gameId": "18014398528053853",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "176.57.170.12",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765085,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 36,
            "max": 64
          },
          "4": {
            "current": 0,
            "max": 2
          }
        },
        "guid": "f2d692ed-1444-4c0d-98c2-cfea0c73c0ad",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "- #1 [WBKS] VANILLA MAPS | NO RULES | FAST VEHICLE SPAWN",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 1,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "XP7_Valley",
        "gameId": "36028797037526240",
        "gameExpansions": [
          17179869184
        ],
        "mapMode": "64",
        "ip": "",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 8
          }
        },
        "guid": "20dc7f9d-4f47-4282-893a-24b1a5c2f01a",
        "port": 0,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "17179869184",
        "name": "!! [vQ37] DICE LA CAMO GET PASSWORD AT FORUMS | vQ37.ORG",
        "settings": {},
        "fairfight": 0,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 4,
        "experience": 1,
        "tickRate": 30,
        "hasPassword": 1,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "fc543a15:8e8fdcdc88a1826ead90cc08ff173f0481974ff6",
        "preset": 1,
        "pingSite": "iad",
        "country": "us"
      },
      {
        "map": "MP_Journey",
        "gameId": "18014398528054308",
        "gameExpansions": [
          0,
          524288,
          1048576,
          17179869184
        ],
        "mapMode": "64",
        "ip": "94.250.199.127",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 64
          }
        },
        "guid": "52be0aba-4290-4096-bd9d-694f6caaa6ff",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "#1|DCS | Tank Wars | Fast Vehichle Respawn Server",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Flooded",
        "gameId": "18014398528054057",
        "gameExpansions": [
          0
        ],
        "mapMode": "8",
        "ip": "",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 10
          }
        },
        "guid": "3cd4efc4-4b49-452c-975b-bc419744420e",
        "port": 0,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "weichis winterwunderland",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 8,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 1,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "34068fe8:3d35637bf425505c8c5f3fcdffd3f162a4b5c089",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Naval",
        "gameId": "18014398528054304",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "108.61.235.37",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 24
          }
        },
        "guid": "d4ccf31d-03d2-4ce6-b48e-84f6c29bed59",
        "port": 30000,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "=BGH= Big Game Hunter | Megalodon Storm",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 1,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "lax",
        "country": "us"
      },
      {
        "map": "MP_Resort",
        "gameId": "18014398528054290",
        "gameExpansions": [
          0,
          524288,
          1048576,
          268435456,
          2097152,
          4194304,
          8388608,
          8589934592,
          17179869184
        ],
        "mapMode": "1",
        "ip": "108.61.121.10",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 32
          }
        },
        "guid": "478a8134-f334-4a47-b38a-9137a345d225",
        "port": 30070,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "!! (THB) The Half Breeds !! All Maps-Noobs\/Avg Players Welcome",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "lax",
        "country": "us"
      },
      {
        "map": "MP_Abandoned",
        "gameId": "18014398528039919",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "136.243.119.204",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765084,
        "slots": {
          "8": {
            "current": 0,
            "max": 4
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 64
          },
          "4": {
            "current": 0,
            "max": 2
          }
        },
        "guid": "ca8b14cf-8955-49e0-8702-a0ad4299c384",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "=[CG]=CraZy GaMeR All BEST MAPS!",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "ru"
      },
      {
        "map": "MP_Prison",
        "gameId": "18014398528054197",
        "gameExpansions": [
          0
        ],
        "mapMode": "32",
        "ip": "176.57.170.34",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765062,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 23,
            "max": 32
          }
        },
        "guid": "5a2e09b7-f9b1-481b-a2c9-f3875ef1e543",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "! [NNC] 24\/7 LOCKER",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Siege",
        "gameId": "36028797037526130",
        "gameExpansions": [
          0,
          524288,
          1048576
        ],
        "mapMode": "64",
        "ip": "62.104.176.129",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 16
          }
        },
        "guid": "746107db-040d-45e2-a530-be6110119f2d",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "Seniorengilde",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Flooded",
        "gameId": "36028797037526098",
        "gameExpansions": [
          0
        ],
        "mapMode": "32",
        "ip": "94.250.199.107",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765077,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 58,
            "max": 64
          }
        },
        "guid": "c4fad2a1-5336-4f1c-9b14-730ff588ff9d",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "SUPER@ [SiC] S5 TDM Team Death Match",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "XP7_Valley",
        "gameId": "36028797037512752",
        "gameExpansions": [
          17179869184,
          0,
          1048576,
          524288,
          268435456,
          2097152,
          8388608,
          4194304
        ],
        "mapMode": "32",
        "ip": "94.250.199.139",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 24
          }
        },
        "guid": "5035fc1a-9143-4a13-9d09-b31a5a36a749",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "17179869184",
        "name": "Devils TD Server only TD   K \/ D bis 1.6 \/ 60 Hz",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 2,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Abandoned",
        "gameId": "18014398528052398",
        "gameExpansions": [
          0,
          524288,
          1048576
        ],
        "mapMode": "1",
        "ip": "173.199.86.102",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 12
          }
        },
        "guid": "0afd9337-6606-4dc2-818a-41d6f62e28b6",
        "port": 30010,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "Friday Night Gamers -  BF4 Server!",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "lax",
        "country": "us"
      },
      {
        "map": "MP_Prison",
        "gameId": "18014398528054109",
        "gameExpansions": [
          0
        ],
        "mapMode": "32",
        "ip": "94.250.208.91",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765064,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 28,
            "max": 32
          }
        },
        "guid": "814953f1-28d7-4abe-811f-d7486d1a7b2d",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "! [EGL]  LOCKER ALL WEAPONS",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 2,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "XP0_Metro",
        "gameId": "18014398528053262",
        "gameExpansions": [
          524288
        ],
        "mapMode": "64",
        "ip": "72.5.195.170",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765077,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 29,
            "max": 48
          }
        },
        "guid": "9a3062d0-b63e-4a89-a7cf-72e43186433b",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "524288",
        "name": "! [TBG] 90HZ | OPERATION METRO - ALL WEAPONS | TBGclan.com",
        "settings": {},
        "fairfight": 1,
        "region": 1,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 1,
        "tickRate": 90,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "lax",
        "country": "us"
      },
      {
        "map": "MP_Abandoned",
        "gameId": "36028797037512560",
        "gameExpansions": [
          0,
          524288
        ],
        "mapMode": "16777216",
        "ip": "94.250.199.54",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 64
          }
        },
        "guid": "41ee2bd9-fab3-4df7-80a6-953f608e75da",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "#1 [FxG] BF4 FR - NORMAL - CONQUEST - 1200 tickets",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "fr"
      },
      {
        "map": "MP_Prison",
        "gameId": "18014398528040603",
        "gameExpansions": [
          0,
          524288
        ],
        "mapMode": "64",
        "ip": "94.250.199.59",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 64
          }
        },
        "guid": "015a57eb-ba87-426c-8d16-563553e3b382",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "Op. Locker and Metro 2014 24h\/24h Hardcore",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "ams",
        "country": "fr"
      },
      {
        "map": "MP_Siege",
        "gameId": "36028797037526304",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "94.250.199.193",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 2
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 3,
            "max": 32
          }
        },
        "guid": "e1f5e808-2d32-413e-b29f-4c1c096b5a17",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "- #5 [WBKS] MixMode - VanillaMapsVote {FastSpawnFly\/Noob}",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Naval",
        "gameId": "36028797037512238",
        "gameExpansions": [
          0
        ],
        "mapMode": "64",
        "ip": "89.163.187.241",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 10
          }
        },
        "guid": "83a243bb-5101-463c-b806-9aaaf7885677",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "#4[..TH..] DICE-camo",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 8,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Abandoned",
        "gameId": "36028797037526139",
        "gameExpansions": [
          0,
          524288,
          2097152,
          1048576,
          4194304
        ],
        "mapMode": "512",
        "ip": "94.250.199.220",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 16
          }
        },
        "guid": "02863823-4193-45e2-a713-e47c4c1b985f",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "BMDs Renterntreffpunkt",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 1,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Tremors",
        "gameId": "18014398528052937",
        "gameExpansions": [
          0,
          524288,
          1048576,
          268435456,
          2097152,
          4194304,
          8388608,
          8589934592,
          17179869184
        ],
        "mapMode": "32",
        "ip": "37.157.251.107",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765052,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 16
          }
        },
        "guid": "746ebb72-5766-4afb-bf58-af0f4025ab68",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "Hardcore Rush,Domination,TDM,Votemap,Vehicle Only Transport",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 120,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 2,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "XP0_Metro",
        "gameId": "18014398528054110",
        "gameExpansions": [
          524288,
          0,
          2097152,
          17179869184,
          268435456
        ],
        "mapMode": "1",
        "ip": "",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 10
          }
        },
        "guid": "f822901d-febb-4537-8136-34f3fc00c357",
        "port": 0,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "524288",
        "name": "### COMBAT-LINIE BF4 ###",
        "settings": {},
        "fairfight": 0,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 8,
        "experience": 0,
        "tickRate": 30,
        "hasPassword": 1,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "8cfc955e:8a34a61289c64ac54408888c31c89f47c4730425",
        "preset": 8,
        "pingSite": "ams",
        "country": "de"
      },
      {
        "map": "MP_Prison",
        "gameId": "18014398528054256",
        "gameExpansions": [
          0
        ],
        "mapMode": "32",
        "ip": "94.250.199.38",
        "matchId": "0",
        "protocolVersionString": "4900",
        "extendedInfo": {
          "message": "",
          "bannerUrl": "",
          "desc": ""
        },
        "game": 2048,
        "ranked": 1,
        "online": 1,
        "platform": 1,
        "tickRateMax": 30,
        "updatedAt": 1621765051,
        "slots": {
          "8": {
            "current": 0,
            "max": 0
          },
          "1": {
            "current": 0,
            "max": 20
          },
          "2": {
            "current": 0,
            "max": 20
          }
        },
        "guid": "d99db8f2-b14e-4287-ad70-3cc845895bc4",
        "port": 25200,
        "punkbuster": 1,
        "playlist": 0,
        "gameExpansion": "0",
        "name": "[FORK] Clan Server",
        "settings": {},
        "fairfight": 1,
        "region": 16,
        "mapVariant": 0,
        "ping": 999,
        "serverType": 2,
        "experience": 0,
        "tickRate": 60,
        "hasPassword": 0,
        "maps": {
          "maps": [],
          "currentMapRound": -1,
          "nextMapIndex": -1,
          "currentMapIndex": -1,
          "numberMapRounds": -1
        },
        "secret": "",
        "preset": 2,
        "pingSite": "ams",
        "country": "de"
      }
    ],
    "systemUtcTime": 1621765085,
    "bf4trialbannerActive": true,
    "staticPrefix": "\/\/cdn.battlelog.com\/bl-cdn\/cdnprefix\/1323197",
    "searchQuery": "",
    "realm": {
      "lang": 1,
      "game": 2048,
      "section": 2048
    },
    "pushConnections": [
      {
        "sslAddress": "beaconpush.battlelog.com",
        "apiKey": "planet",
        "nodeNumber": 0,
        "channelsWithAuth": [
          "1621808285;7ffe7cd23032e7df11479ca2ecd6218ba99a21f6bp:user"
        ],
        "sslEnabled": true,
        "sslWsAddress": "beaconpush.battlelog.com",
        "channels": [
          "bp:user"
        ],
        "token": "1621808285;3ca50d82bd4c6108b30e95396733ccc0e6b77200",
        "user": "guest_1621656239.35",
        "address": "beaconpush.battlelog.com",
        "wsAddress": "beaconpush.battlelog.com",
        "log": false
      }
    ],
    "isBFHVisible": true,
    "platform": 1,
    "requestURI": "http:\/\/battlelog.battlefield.com\/bf4\/serverbrowserwarsaw",
    "serverbrowserTab": "index",
    "forceExpandedFilter": 0,
    "pushOperator": "planet",
    "writeBanUntil": 0,
    "componentName": "serverbrowserwarsaw",
    "hasWriteBan": false,
    "activeMenu": "multiplayer",
    "filePrefix": "\/\/d34ymitoc1pg7m.cloudfront.net",
    "favGuids": [],
    "isAjaxNavigation": true,
    "actionName": "index",
    "isSecure": true,
    "banType": 0,
    "hideComcenter": false,
    "clientIp": "36.73.34.105",
    "bfhbetabannerActive": false
  },
  "context": {
    "searchQuery": "",
    "_href": "\/bf4\/serverbrowserwarsaw\/",
    "searchUsers": [],
    "userPlatform": 1,
    "notification": null,
    "logClientSideErrors": false,
    "validXpacks": [
      "xp1",
      "xp0",
      "xp2",
      "xp3",
      "xp4"
    ],
    "filter": {
      "playlists": [],
      "tickRates": [],
      "modeRotation": -1,
      "pingSite": null,
      "commanderSlots": [],
      "ranked": -1,
      "spectatorGameSize": [],
      "protocolVersionString": "4900",
      "gamepresets": [],
      "game": 2048,
      "gamemodes": [],
      "experiences": [],
      "platform": 1,
      "filtered": 1,
      "premium": -1,
      "slots": [],
      "serverTypes": [],
      "maps": [],
      "password": -1,
      "useAdvanced": -1,
      "name": "",
      "gameexpansions": null,
      "gameSize": [],
      "country": [],
      "commanderGameSize": [],
      "settings": [],
      "useLocation": -1,
      "regions": [],
      "excludeExpansions": [],
      "includeExpansions": [],
      "spectatorSlots": [],
      "maxPlayers": null,
      "mapRotation": -1
    },
    "platform": 1,
    "serverbrowserAction": "serverbrowser-action-index",
    "userMessageBox": null,
    "platformString": "pc",
    "searchPersonas": [],
    "enableVideoBackground": "0",
    "servers": [],
    "onGoingXpEvent": {
      "licenses": [
        "None"
      ],
      "start": 1621681200,
      "end": 1621854000,
      "license": "",
      "multiplier": 2.0
    },
    "titleSection": "Battlefield 4"
  }
}
